# Use OpenJDK 8 as the base image
FROM openjdk:8

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Maven build
COPY taxi-booking/target/taxi-booking-1.0-SNAPSHOT.jar app.jar

# Run the JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
